<?php
use Drupal\advanceentitiesautocomplete\Advanceentitiesautocomplete;

/**
 *
 * @file
 * Primary module hooks for advanceentitiesautocomplete module.
 */

/**
 * Implements hook_element_info_alter().
 *
 * @see Drupal\Core\Field\Plugin\Field\FieldWidget\EntityReferenceAutocompleteWidget
 */
function advanceentitiesautocomplete_element_info_alter(&$type) {
  if (isset($type['entity_autocomplete'])) {
    $type['entity_autocomplete']['#process'][] = [
      Advanceentitiesautocomplete::class,
      'processEntityAutocompleteCustom'
    ];
  }
}



